import pandas as pd
import numpy as np

def engineer_features(df: pd.DataFrame, is_training: bool = True) -> pd.DataFrame:
    """
    Transforms raw access logs into machine-learning-ready features.
    Handles temporal, sequence, and behavioral derivations.
    """
    df = df.copy()
    
    # 0. Graceful Fallbacks for missing generator columns
    if 'session_duration' not in df.columns:
        # Impute missing session durations with a standard default (e.g., 60 seconds)
        df['session_duration'] = 60.0
        
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df = df.sort_values(by=['entity_id', 'timestamp'])

    # 1. Temporal Features
    df['hour_of_day'] = df['timestamp'].dt.hour
    df['day_of_week'] = df['timestamp'].dt.dayofweek
    df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)
    df['is_off_hours'] = ((df['hour_of_day'] < 7) | (df['hour_of_day'] > 19)).astype(int)

    # 2. Sequence/Velocity Features (Impossible Travel & Brute Force)
    # Time since last event per entity
    df['time_since_last_event_sec'] = df.groupby('entity_id')['timestamp'].diff().dt.total_seconds().fillna(0)
    
    # Auth failure rolling count (simulate a 5-event window)
    df['is_failure'] = (df.get('auth_result', 'SUCCESS') != 'SUCCESS').astype(int)
    df['recent_auth_failures'] = df.groupby('entity_id')['is_failure'].transform(
        lambda x: x.rolling(window=5, min_periods=1).sum()
    )

    # 3. Behavioral / Footprint Features (Device Spoofing & Lateral Movement)
    # Has this entity used this device before?
    # Added fallback just in case device_fingerprint is also missing
    if 'device_fingerprint' not in df.columns:
        df['device_fingerprint'] = 'unknown_device'
        
    df['is_new_device'] = (~df.duplicated(subset=['entity_id', 'device_fingerprint'])).astype(int)
    
    # Running count of distinct resources accessed by the entity
    if 'resource_accessed' in df.columns:
        df['resource_category'] = df['resource_accessed'].astype('category').cat.codes
    else:
        df['resource_category'] = 0
        
    # Fill NAs generated by rolling windows and diffs
    df = df.fillna(0)
    
    return df

def get_feature_columns():
    return [
        'hour_of_day', 'is_weekend', 'is_off_hours', 'time_since_last_event_sec',
        'recent_auth_failures', 'is_new_device', 'session_duration', 'resource_category'
    ]